import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://sqiirrmfdnclkcuvmrqf.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxaWlycm1mZG5jbGtjdXZtcnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjMxNDEsImV4cCI6MjA2NzAzOTE0MX0.RMnenY0oyNNT61MWx9Q7XGNOYsJH9aZSuUc8uUM1vM8')